### ISSUE TITLE
prettified html output

### ISSUE THREAD

**Issue by sillyslux** [markdalgleish/static-site-generator-webpack-plugin#107]
coming from "opinionated" gatsby.js i want prettified html output (b/c git diffs)
so currently i use a modified static-site-generator-webpack-plugin from v2.1.1
```
var prettifier = require('js-beautify').html;
compiler.assets[outputFileName] = createAssetFromContents(prettifier(output));
```
see https://github.com/markdalgleish/static-site-generator-webpack-plugin/blob/v2.1.1/index.js#L63
but since i don't know how and when gatsby will update this dependency, i don't even know if it makes sense at all...

**Comment by eloytoro** [comment]
you shouldn't be versioning the output files in my opinion

**Comment by sillyslux** [comment]
@eloytoro well then go and tell github to disable versioning on gh-pages branches if you really think so.
right now, i couldn't avoid it even if you had convinced me with your well-founded opinion.
no matter what you think of it, it's nice for me to see when a small modification also resulted in a small diff.
but above all: there's nothing wrong with versioning anything. ever.

**Comment by eloytoro** [comment]
Either way you could just require the prettifier in your render function
and return the output of that.

Basically what you're showing in the example but in your render function
instead of directly into the plugin

On Aug 6, 2017 8:35 AM, "sillyslux" <notifications@github.com> wrote:

@eloytoro <https://github.com/eloytoro> well then go and tell github to
disable versioning on gh-pages branches if you really think so.
right now, i couldn't avoid it even if you had convinced me with your
well-founded opinion.
no matter what you think of it, it's nice for me to see when a small
modification also resulted in a small diff.
but above all: there's nothing wrong with versioning anything. ever.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/107#issuecomment-320507385>,
or mute the thread

**Comment by jahredhope** [comment]
It seems like the issue of formatting the render output is solved by the consumer being able to output formatted HTML from their render function.
Closing the issue for now. Please re-open if this is not solved.
