### ISSUE TITLE
Feedback?

### ISSUE THREAD

**Issue by markdalgleish** [markdalgleish/static-site-generator-webpack-plugin#2]
This is only v1.0 of the project, so I'd really appreciate any feedback.

cc @gaearon @kyleamathews

**Comment by KyleAMathews** [comment]
Inviting @WickyNilliams as we've chatted about this on Twitter several times.

**Comment by KyleAMathews** [comment]
Static sites built with React is something I've been thinking a ton about actually so thanks for sharing with us your explorations Mark and inviting us to the discussion. I haven't got to the point where I'm writing code but for my [startup](https://relaterocket.co), I need to build in the next few months several blogs, doc, marketing sites, etc. and I think using a React.js powered static site generator would be ideal for all of them. I write everything web related these days in React and a React/React-Router/Hot-Loader based static site generator would have some really unique and valuable properties.

Here's a quick braindump of directions I've been thinking.

* Configuration/Convention driven but easily overridable with code. What this means in practice is that there'd be a command line tool with commands to create/watch/build sites. Most sites wouldn't need anything special for configuration so there'd be a common webpack etc configurations bundled with the cli tool that would set up hot reloading while developing and uglified builds for production.
* RSS/Atom support — necessary for anything blog like
* no reload page transitions. This would be amazing and pretty easy to do with React Router. The initial html page would load followed quickly by a js bundle with the content for the rest of the site. Atlassian's Git tutorial site does this and it feels amazing (built with React/React-Router as well) https://www.atlassian.com/git. CircleCi almost gets this right but they load content for each page individually which delay causes noticable layout jerk https://circleci.com/docs/getting-started
* smart code splitting. E.g. autostart splitting if bundle gets larger than 750kb. A fun research project would be to investigate how to use internal link structure to generate ideal bundles e.g. for each page, bundle together all content within 2 clicks of page. We'd handle loading additional bundles automatically.
* themes that are installable separately. E.g. for blogs/doc sites, etc. This would leverage react router by wrapping page content inside it. So a blog theme would provide a header, navigation, background colors/images/etc and put the child blog post inside it.
* Support Markdown/Asciidoctor/other writing formats
* rehabilitate https://github.com/andreypopp/reactdown and give it 1st class support
* each page can have its own package.json. Useful for marketing sites where one or two pages might have lots of extra stuff or blog posts where you want to drop live demos in.
* no configuration routing. Just use the directory structure of posts (`posts/a-long-voyage-across-the-southern-seas/index.md`) to auto-generate the react-router configuration.
* A docker image that autobuilds/server site. My startup uses Docker containers for running microservices so the ideal setup for me would be to develop locally and then push the src which would get added to a Docker image, built there, and get served by Nginx.
* plugins support e.g. simple client-side search for a blog. Extract text from markdown and make searchable with http://lunrjs.com/
* built-in support for my [typography tool](https://github.com/KyleAMathews/typography.js). There could be a number of builtin typography "themes".

There's a lot of static site generators out there and I've played with several and written my own for my blog. They're all pretty much the same and not particularly interesting. I think a React.js based SSG can push the state of the art in three ways — easy no-page transitions, react.js style components, and leveraging the growing react.js ecosystem of tools and components.

Most stuff on the web are sites not apps. And react.js components as just as powerful for sites as they are apps so a kickass tool for building react.js sites would be very valuable.

**Comment by KyleAMathews** [comment]
I've done some brainstorming on what the tool's name should be. The best I've come up with is `codex` which was the original name for "book" in Latin when it was invented around 100AD. A codex is a bound collection of pages which I thought was a neat metaphor for what the tool does. I registered https://github.com/codices.

**Comment by KyleAMathews** [comment]
Adding @vjeux as he's talked about this on Twitter, @BradDenver as he's built a react.js static site generator, and @jordwalke as he wrote most of react-page.

**Comment by markdalgleish** [comment]
The aim of this project was to be more of a minimal building block for webpack-based static sites, rather than a traditional static site generator. I'm trying to make it easy to take your webpack/isomorphic React Router workflow and easily port it to a static site.

All of the ideas you've listed are really great, but I think they'd be better suited to a more opinionated project, perhaps built on top of this foundational layer. Maybe you could start building one and see if there's any functionality missing? I imagine you'd find even more opportunities for smaller packages that solve individual problems.

**Comment by KyleAMathews** [comment]
Cool, fair enough. I'll definitely evaluate using this code as a foundational piece when I start building out Codex.

**Comment by cgreening** [comment]
I've made some mods in my fork - I wanted to be able to control where the files were output to. So I've modifed it so that you can pass in an array of paths and destinations:

e.g.

```js
[
  { path: '/hello/', dest: 'hello.html' },
  { path: '/world/', dest: 'world.html' }
]
```

My main reason for doing this was getting it working nicely with react router - when I was outputting to `/hello/index.html` none of my assets were found as they were one directory up.

This can be fixed by adding an html base to the generated html, but that's a bit messy I think.

Other issues I had are mainly due to other modules trying to do document writes - which obviously don't work. These seemed to be ones that were trying to handle their own styles and were bypassing my css loaders completely.

Also seemed to have problems getting error messages out - I think somewhere either it's crapping out too early so things like compilation errors are not getting output or they are being lost somewhere.

**Comment by cgreening** [comment]
Think I have fixed the errors not reporting in my latest commit.

```js
        return Promise
          .fromNode(render.bind(null, locals))
          .then(function(result) {
            compiler.assets[outputFileName] = createAssetFromContents(result);
          }, function(error) {
            compiler.errors.push(error);
          });
```

**Comment by Fenntasy** [comment]
@cgreening How do you manage your routes then ? 
<Route path="/hello.html" handler={Hello} />  ?

I'm really not sure this is the way of managing  assets either, they're all packed on the root directory and renamed with a hash. 

I tried this static generation (mostly) in order to have a better SEO but it just nullifies the SEO of images and it's just a awful mess if you have a bunch. 

Wouldn't it be possible to have a way of specifying the asset directory, keeping the original filenames and maybe have a react-asset component that take into account the path where it is supposed to be ?

Although i'm missing something, I really think this is the path to go to. And not this mess with everything in one directory. 

I know this subject seems old but if you have any insights, i'd be glad to hear it.

**Comment by cgreening** [comment]
@Fenntasy In the end I went with a bit of a hack - the only links between the static pages I was generating was in the nav header, so I created a static version of that with links - e.g.

landing.html, faq,html, docs.html etc..

These pages are generated using the static site generator.

I then use these generated pages as templates for the `HtmlWebpackPlugin` in my normal webpack build  so I get the statically generated html for SEO and the dynamic content if a user lands on the page.

So my webpack build runs in two stages, the first stage builds the static html template files, the second stage builds the javascript and injects it into the template files.

When google hits the page it see the static html and the static links in the nav bar so it can spider the pages.

When a user lands on the page, they get the initially rendered static HTML and then once react starts it picks up from there - I think there is probably something not quite right at this point as react spits out a warning as the static html doesn't match exactly what it's expecting so it re-renders everything.

The static nav is a bit of a pain as I have to make sure I keep in sync with the dynamic version, but I'm wondering if it might be possible to be a bit more clever by using the DefinePlugin to pass in some flags during static generation to make the `makeHref` function behave a bit differently.

Not perfect - but it's currently doing the job.

You can see it working here:

https://www.nodule.io - still very much a work in progress.

I've got (yet another!) hack so that when a user lands on one of these static pages the URL is changed to my normal static URL so that if they bookmark the page they don't end up with the wrong URL.

**Comment by KyleAMathews** [comment]
@cgreening @Fenntasy I've put a *lot* of work into solving these sorts of navigation/linking/static->dynamic troubles with [Gatsby](https://github.com/gatsbyjs/gatsby). Things just (mostly) work now. Would love your help over there!

**Comment by cgreening** [comment]
@KyleAMathews Looks interesting - next step for my site is to add a blog so I will give it a go.

**Comment by Fenntasy** [comment]
@cgreening Yeah, and you have these wonderful image files as 3c945af03e6d13e4cc327d08b3035e9f.svg that google will see and index but you will lose a big chunk of metadata. Sure you could try to count on the indexing of title or other aria accessibility but still a shame. Seems like a pain in the ass to use react for that result.

@KyleAMathews Same for me, i'll look into it.

**Comment by KyleAMathews** [comment]
cool :) things are still early so missing docs + bugs so file issues early.
