### ISSUE TITLE
Build .html file *without* a correlating .js file?

### ISSUE THREAD

**Issue by altruisticsoftware** [markdalgleish/static-site-generator-webpack-plugin#66]
Hey there.

Are we not able to generate the html files without a js file for each one?

For example, could this:
```
        entry: {
            'splash-page': './src/static/splash_page.ts',
            'app-index': './src/static/app_index.ts',
        }
```
just output:
```
/splash_page.html
/index.html
```
**not**
```
/splash-page.html
/splash-page.js
/app-index.html
/app-index.js
```

Thanks!

**Comment by ghost** [comment]
Hi, I see that it's been a while, but I think I have de solution. I'm using the Static site generator webpack plugin to build html files, and I needed a clean output directory. 

Your situation is a little different from mine because in your case, each JS file is an entry. For my part, I used the "crawl" option of the plugin to crawl all the pages of my router, and generate an HTML file per page.

So I have only one entry (called main), and only one chunk file generated by the plugin (main.js). 

But I was able to delete it with the "SuppressChunksPlugin" plugin. It removes all specified useless chunks generated by webpack. 

Here is the corresponding section of my webpack.config.js file : 
```js
//HTML Configuration
var htmlConfig = Object.assign({}, config, {

  entry: {
    main: path.resolve(__dirname, 'src/index.js'),
  },

  output: {
    filename: 'webpack_build.js',
    path: path.resolve(__dirname, 'dist/html'),
    libraryTarget: 'umd'
  },
  module: {
    rules: [
      {
        use: ['babel-loader']
      }
    ]
  },

  plugins: [
    new StaticSiteGeneratorPlugin({
      entry: 'main',
      crawl: true,
      globals: {
        window: {}
      }
    }),
    new SuppressChunksPlugin(['main']),
    new webpack.DefinePlugin({
      BUILDDATE: 'JSON.stringify(new Date())'
    })
  ]
})
```

You just have to call the name of your entry, and this plugin will remove the unwanted files for you. The plugin is taking an array of entries. So I think in your case, you can pass all the defined entries to the plugin.

**Comment by remnantdotdev** [comment]
Thanks @Kalagounet, however I've since fell in love with [nextjs](https://nextjs.org/) in case anyone else is interested in a solid site generator.

**Comment by ghost** [comment]
I agree with you @altruisticsoftware. If it is to generate a static site, NextJs (or Gatsby why not) it's not even comparable.

Personally I use NextJs and Static webpack generator site for two different things. I think this plugin alone is useful for generating clean HTML files and sources, like a template engine.

And NextJs, Gatsby, or whatever are more complete for the development of websites and web applications.
